[phases.setup]
  run = "echo Setup phase"

[phases.install]
  run = "pip install -r requirements.txt"

[phases.build]
  run = "echo Build phase"

[phases.start]
  run = "python sign_bridge_server.py"

[metadata]
  platform = "python"
